apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mycv-project
  source:
    repoURL: https://github.com/devabolmasov/argo-helm
    targetRevision: main
    path: test
    helm:
      values: |
        replicaCount: 1
        service:
          port: 80
          targetPort: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-nginx-app
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true 