apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mycv-project
  source:
    repoURL: https://github.com/devabolmasov/argo-helm
    targetRevision: main
    path: /test/
    helm:
      values: |
        replicaCount: 2
        service:
          port: 8081
          targetPort: 8081
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}