apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mycv-project
  source:
    repoURL: https://github.com/devabolmasov/argo-helm
    targetRevision: main
    path: test
    helm:
      values: |
        replicaCount: 1
        service:
          port: 80
          targetPort: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}